export const ch2P3Markdown = `
As stated in the official documentation, \`angular.json\` is a file at the root level of an Angular workspace that gives workspace-wide and project-specific configuration defaults for build and development tools. When we use the command \`ng new <project-name>\` , a new workspace is created as the root level of the project folder automatically. Hence, the command also generates the \`angular.json\` file.

Let's now open up the \`angular.json\` file of the \`my-dummy-application\` application (or any  application generated by the Angular CLI). You can see that the file includes crucial information about the application, including the name, type, root path and source root path:

![angular.json file preview](/assets/images/ch2/angular_json_preview.png)

With the \`angular.json\` file, we can configure our Angular CLI for a particular workspace. For example, we may want the CLI to generate SCSS files for new components inside our \`my-dummy-application\` project. For that, we can search for the keyword \`schematics\` inside \`angular.json\` and add the option as shown below:

\`\`\`javascript
"schematics": {
  "@schematics/angular:component": {
    "style": "scss"
  }
}
\`\`\`

After saving this, if we try to generate a new component, a \`.scss\` file would be created instead of a \`.css\` file:

![scss file generated](/assets/images/ch2/scss_generated.png)

You can read more about \`angular.json\` configuration in [the official documentation here](https://angular.io/guide/workspace-config).
`;